# Generated by Django 6.0.2 on 2026-03-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
    ]
