# Generated by Django 6.0.2 on 2026-03-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_book_is_bestseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена книги в евро. Должно быть больше 0', max_digits=5, null=True, verbose_name='Цена книги со скидкой'),
        ),
    ]
